server:
  port: 8081
  servlet:
    context-path: /customer-service

spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  data:
    mongodb:
      user: test
      password: test
      uri: mongodb://localhost:27017/customer-service
      auto-index-creation: true